/**
 * Centralised UI copy — edit here without touching components.
 */
export const copy = {
  brand: {
    name: 'Mithaava',
  },
  landing: {
    headline: 'Fresh cakes, baked in Sector 46.',
    subline: 'Browse the menu, then confirm delivery at checkout.',
    pincodeHelper: 'We deliver within 10 km of Sector 46, Gurugram',
    eyebrow: 'Premium cakes · Freshly baked · Delivered with love',
    scriptLine: 'Indulge the Sweetness of Happiness',
    specialsLabel: 'Mithaava Specials',
    bestSeller: 'Best seller',
    orderNow: 'Order now',
    benefits: [
      { id: 'fresh', title: 'Freshly baked', body: 'Everyday' },
      { id: 'delivery', title: 'Quick delivery', body: 'Within 10 km' },
      { id: 'hours', title: 'Open 24 hours', body: 'Order anytime' },
      { id: 'love', title: 'Made with love', body: 'For celebrations' },
    ],
  },
  pincode: {
    label: 'Pincode',
    placeholder: '122xxx',
    invalid: 'Enter a 6-digit pincode',
    serviceable: (pincode: string) => `We deliver to ${pincode}`,
    unserviceable: (pincode: string) =>
      `We don't deliver to ${pincode} directly yet. You can still order Mithaava cakes on Swiggy or Zomato.`,
    tryAnother: 'Try another pincode',
    startShopping: 'Start shopping',
    change: 'Change',
    deliveringTo: (pincode: string) => `Delivering to ${pincode}`,
  },
  aggregators: {
    strip: 'Also on Swiggy & Zomato for a better delivery experience',
    primaryOutside: 'Order on Swiggy or Zomato',
  },
  menu: {
    searchPlaceholder: 'Search cakes',
    searchEmpty: (query: string) =>
      `No cakes match '${query}'. Try 'chocolate' or 'fruit'.`,
    notAvailable: 'Not available',
    orderHoursAhead: (hours: number) => `Order ${hours} hours ahead`,
    addToCart: 'Add to cart',
    youMayAlsoLike: 'You may also like',
  },
  favourites: {
    title: 'Your favourites',
    add: 'Add to favourites',
    remove: 'Remove from favourites',
    added: 'Saved to favourites',
    removed: 'Removed from favourites',
    empty: 'Tap the heart on a cake to save it here.',
    nav: 'Favourites',
  },
  cart: {
    title: 'Your cart',
    empty: 'Your cart is empty',
    emptyAction: 'Browse the menu',
    continue: 'Continue to details',
    deliveryNote: 'Delivery charges are confirmed on WhatsApp',
    leadTimeNotice: (label: string, hours: number) =>
      `Your cart has a ${label} cake. Earliest delivery is ${hours} hours from now`,
    viewCart: 'View cart',
    itemsSummary: (count: number, total: string) =>
      `${count} ${count === 1 ? 'item' : 'items'} · ${total}`,
    undoRemove: 'Undo',
    removed: 'Removed from cart',
  },
  checkout: {
    title: 'Checkout',
    yourDetails: 'Your details',
    delivery: 'Delivery',
    cakeMessageAndNotes: 'Cake message and notes',
    review: 'Review',
    fullName: 'Full name',
    mobile: 'Mobile',
    address: 'Full address',
    landmark: 'Landmark (optional)',
    pincode: 'Pincode',
    deliveryDate: 'Delivery date',
    timeSlot: 'Time slot',
    cakeMessage: 'Message on cake (optional)',
    notes: 'Extra notes (optional)',
    clearSaved: 'Clear saved details',
    sendWhatsApp: 'Send order on WhatsApp',
    nameRequired: 'Enter your full name',
    mobileInvalid: 'Enter a 10-digit Indian mobile number starting with 6–9',
    addressMin: 'Enter an address of at least 10 characters',
    slotRequired: 'Choose a delivery date and time slot',
    cakeMessageMax: 'Keep the cake message under 40 characters',
    notesMax: 'Keep notes under 200 characters',
  },
  orderSent: {
    title: 'WhatsApp is open with your order. Tap send there to confirm it with us.',
    openAgain: 'Open WhatsApp again',
    copyText: 'Copy order text',
    clearCart: "I've sent it, clear my cart",
    backToMenu: 'Back to menu',
    orderId: (id: string) => `Order ${id}`,
  },
  contact: {
    title: 'Contact us',
    subline:
      'Tell us what you need — we will continue the conversation on WhatsApp.',
    name: 'Your name',
    address: 'Your address',
    message: 'Your message',
    messagePlaceholder: 'Custom cake, catering, timing, or any question…',
    sendWhatsApp: 'Send on WhatsApp',
    nameRequired: 'Enter your name',
    addressMin: 'Enter an address of at least 10 characters',
    messageMin: 'Write a short message (at least 10 characters)',
    messageMax: 'Keep the message under 500 characters',
    visitHint: 'Or visit us in Sector 46 — we are open 24 hours.',
  },
  footer: {
    copyright: (year: number) => `© ${year} Mithaava`,
    fssai: 'FSSAI',
  },
  notFound: {
    title: 'This page rolled off the tray',
    body: 'The link may be outdated. Head back to the menu for fresh cakes.',
    action: 'Back to menu',
  },
  a11y: {
    cart: 'Cart',
    favourites: 'Favourites',
    search: 'Search cakes',
    close: 'Close',
  },
} as const;
